repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.12.9
    hooks:
      - id: ruff
        # don't pass explicit "check ." here; pre-commit will invoke ruff with the
        # staged filenames. Passing `check` and `.` can make ruff treat them as a
        # filename on Windows/UNC paths and produce E902 (os error 2).
        # args: ["check", "."]
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
