name: Generate lockfile

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install build tools (apt)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3-dev
      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Dump installed packages
        run: |
          pip freeze > requirements.lock.txt
      - name: Upload lockfile
        uses: actions/upload-artifact@v4
        with:
          name: requirements-lock
          path: requirements.lock.txt
