name: Update lockfile

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 0' # weekly

jobs:
  update-lock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3-dev
      - name: Install requirements and produce lockfile
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip freeze > requirements.lock.txt
      - name: Commit and create PR
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update requirements.lock.txt"
          branch: update/requirements-lock
          title: "Update requirements.lock.txt"
          body: |
            This PR updates the pinned dependencies in requirements.lock.txt
            and was created automatically by the Update lockfile workflow.
